on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    uses: sliit-foss/fcsc-web/.github/workflows/firebase-deploy.yaml@9044da5f62a6a7317157667ff093a371b520a07e
    with:
      node-version: '14.x'
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
