on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    uses: sliit-foss/fcsc-web/.github/workflows/firebase-deploy.yaml@0cd5415e613f430cc831ff2b9e70c7a8f1927829
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
